.......
======================================================================
FAIL: test_badname_error (__main__.TestBufServer) [If your server behaved as required, our test client will terminate with exit status 0.]
Test to see if server sends back correct error message when client connects with bad name.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "server_test.py", line 338, in test_badname_error
    self.assertTrue(cstatus == 0)
AssertionError: False is not true

======================================================================
FAIL: test_long_msg (__main__.TestBufServer) [If your server behaved as required, our test client will terminate with exit status 0.]
Client sends excessively long message
----------------------------------------------------------------------
Traceback (most recent call last):
  File "server_test.py", line 222, in test_long_msg
    self.assertTrue(cstatus == 0)
AssertionError: False is not true

======================================================================
FAIL: test_long_name (__main__.TestBufServer) [No Address/Leak Sanitizer errors should occur]
Client sends excessively long user name
----------------------------------------------------------------------
Traceback (most recent call last):
  File "server_test.py", line 170, in test_long_name
    self.assertNotIn(b'Sanitizer', serr)
AssertionError: b'Sanitizer' unexpectedly found in b'\n=================================================================\n==32213==ERROR: LeakSanitizer: detected memory leaks\n\nDirect leak of 68 byte(s) in 1 object(s) allocated from:\n    #0 0x7f53d7674b40 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb40)\n    #1 0x56497842a2d8 in get_message /csc209-w20/tutorials/w20/mark_a4/socket.c:134\n    #2 0x56497842ab88 in set_username /csc209-w20/tutorials/w20/mark_a4/chat_helpers.c:138\n    #3 0x564978428677 in main /csc209-w20/tutorials/w20/mark_a4/chat_server.c:210\n    #4 0x7f53d71c6b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)\n\nSUMMARY: AddressSanitizer: 68 byte(s) leaked in 1 allocation(s).\n'

======================================================================
FAIL: test_username_with_space (__main__.TestBufServer) [No Address/Leak Sanitizer errors should occur]
Client sends username with a space
----------------------------------------------------------------------
Traceback (most recent call last):
  File "server_test.py", line 82, in test_username_with_space
    self.assertNotIn(b'Sanitizer', serr)
AssertionError: b'Sanitizer' unexpectedly found in b'\n=================================================================\n==32228==ERROR: LeakSanitizer: detected memory leaks\n\nDirect leak of 11 byte(s) in 1 object(s) allocated from:\n    #0 0x7f795ccedb40 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb40)\n    #1 0x555749f672d8 in get_message /csc209-w20/tutorials/w20/mark_a4/socket.c:134\n    #2 0x555749f67b88 in set_username /csc209-w20/tutorials/w20/mark_a4/chat_helpers.c:138\n    #3 0x555749f65677 in main /csc209-w20/tutorials/w20/mark_a4/chat_server.c:210\n    #4 0x7f795c83fb96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)\n\nSUMMARY: AddressSanitizer: 11 byte(s) leaked in 1 allocation(s).\n'

----------------------------------------------------------------------
Ran 11 tests in 5.397s

FAILED (failures=4)
